import { Types, email } from './types'

email()
  .to('john.doe@example.com')
  .subject('hello')
  .body('hi john doe')
  .plugin(Types.CC, Types.Attachment)
  .attachment('Hello')
  .attachment('Hello2')
  // .cc('1@example.com')
  // .cc('2@example.com')
  // .cc('3@example.com')
  // .cc('4@example.com')
  // .cc('5@example.com')
  // .cc('6@example.com')
  // .cc('7@example.com')
  // .cc('8@example.com')
  // .cc('9@example.com')
  // .cc('10@example.com')
  // .cc('11@example.com')
  // .cc('12@example.com')
  // .cc('13@example.com')
  // .cc('14@example.com')
  // .cc('15@example.com')
  // .cc('16@example.com')
  // .cc('17@example.com')
  // .cc('18@example.com')
  // .cc('19@example.com')
  // .cc('20@example.com')
  // .cc('21@example.com')
  // .cc('22@example.com')
  // .cc('23@example.com')
  // .cc('24@example.com')
  // .cc('25@example.com')
  // .cc('26@example.com')
  // .cc('27@example.com')
  // .cc('28@example.com')
  // .cc('29@example.com')
  // .cc('30@example.com')
  // .cc('31@example.com')
  // .cc('32@example.com')
  // .cc('33@example.com')
  // .cc('34@example.com')
  // .cc('35@example.com')
  // .cc('35@example.com')
  // .cc('35@example.com')
  // .cc('35@example.com')
  // .cc('35@example.com')
  // .cc('35@example.com')
  // .send()

// const newEmail2 = next<{ log: []; state: { sent: false; cc: [] } }>({
//   log: [],
//   state: { sent: false, cc: [] }
// })
//   .to('john.doe@example.com')
//   .subject('hello')
//   .body('hi john doe')
//   .cc('one@example.com')
//   .send()

// console.log(newEmail)
// console.log(newEmail2)
